# Generated by Django 3.2.25 on 2024-09-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240909_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='img',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='schdule',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.TextField(),
        ),
    ]
