# Generated by Django 3.2.25 on 2024-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240909_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
